version: '3.8'

services:

  db:
    image: postgres:15-alpine
    container_name: smart_booking_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: smart_booking_db
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  app:
    build: .
    container_name: smart_booking_app
    restart: always
    ports:
      - "8085:8080"
    environment:
      - DB_HOST=db
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/smart_booking_db
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - RESEND_API_KEY=${RESEND_API_KEY}
    volumes:
      - room_uploads:/app/uploads
    depends_on:
      - db
    extra_hosts:
      - "host.docker.internal:host-gateway"


  adminer:
    image: adminer
    container_name: smart_booking_adminer
    restart: always
    ports:
      - "8086:8080"
    depends_on:
      - db


  tunnel:
    container_name: cloudflared-tunnel
    image: cloudflare/cloudflared:latest
    restart: always
    command: tunnel --no-autoupdate run --token ${TUNNEL_TOKEN}
    depends_on:
      - app

volumes:
  postgres_data:
  room_uploads: