version: '3.8'

services:

  db:
    image: postgres:15-alpine
    container_name: smart_booking_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: smart_booking_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  app:
    build: .
    container_name: smart_booking_app
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/smart_booking_db
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db


  adminer:
    image: adminer
    container_name: smart_booking_adminer
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - db


  tunnel:
    container_name: cloudflared-tunnel
    image: cloudflare/cloudflared:latest
    restart: always
    command: tunnel --no-autoupdate run --token eyJhIjoiODA1NzBmMmIzMTZlZmZiMTg4YmE3MmRjODcyM2FhMTIiLCJ0IjoiMGMxOGU3NDAtNzhmYi00NGE2LWEyZjMtNWQ0OTU2MmIxOTg2IiwicyI6IlpqVTVabVF3WVdVdE5EZGxNeTAwWkdKa0xXRmxaREF0T1RCa05qSTJaVE13WXpoaSJ9
    depends_on:
      - app

volumes:
  postgres_data: