spring:
  application:
    name: smartbooking

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/smart_booking_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email
              - https://www.googleapis.com/auth/calendar.events
              - https://www.googleapis.com/auth/calendar.readonly
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth?prompt=consent&access_type=offline

app:
  security:
    encryption-key: ${ENCRYPTION_KEY}
  base-url: https://book-a-meeting.site

resend:
  api-key: ${RESEND_API_KEY}
  from-email: invites@book-a-meeting.site

server:
  forward-headers-strategy: framework